package:
  create:
    set:
      image_repository: "ghcr.io/justinthelaw/gpu-support-test"
      image_version: 0.1.0
      name: gpu-support-test
    max_package_size: "1000000000"
  deploy:
    set:
      image_repository: "ghcr.io/justinthelaw/gpu-support-test"
      image_version: 0.1.0