apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-support-test
  namespace: leapfrogai
spec:
  runtimeClassName: nvidia
  selector:
    matchLabels:
      app: gpu-support-test
  replicas: 1
  template:
    metadata:
      labels:
        app: gpu-support-test
    spec:
      containers:
        - name: gpu-support-test
          image: "###ZARF_VAR_IMAGE_REPOSITORY###:###ZARF_VAR_IMAGE_VERSION###"
          resources:
            requests:
              memory: 0
              cpu: 0
              nvidia.com/gpu: "###ZARF_VAR_NUMBER_OF_EXPECTED_GPU###"
            limits:
              memory: 0
              cpu: 0
              nvidia.com/gpu: "###ZARF_VAR_NUMBER_OF_EXPECTED_GPU###"
