apiVersion: apps/v1
kind: Deployment
metadata:
  name: "###ZARF_PKG_TMPL_NAME###"
  namespace: leapfrogai
spec:
  selector:
    matchLabels:
      app: "###ZARF_PKG_TMPL_NAME###"
  replicas: 1
  template:
    metadata:
      labels:
        app: "###ZARF_PKG_TMPL_NAME###"
    spec:
      containers:
        - name: "###ZARF_PKG_TMPL_NAME###"
          image: "ghcr.io/justinthelaw/###ZARF_PKG_TMPL_NAME###:###ZARF_VAR_IMAGE_VERSION###"
          resources:
            requests:
              memory: 0
              cpu: 0
            limits:
              memory: 0
              cpu: 0
